// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsqzlckedpbroobjmrny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzcXpsY2tlZHBicm9vYmptcm55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzIyMjksImV4cCI6MjA1OTk0ODIyOX0.UTxUaxKKa-CbCgm8OnQ8hLHHX2-T3EJJ3D7jl7XCaoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);